### ISSUE TITLE
fatal: repository '~/Workspace/tree-sitter-mlx' does not exist

### ISSUE THREAD

**Issue by dmtrKovalenko** [ocaml-mlx/ocaml_mlx.nvim#1]
  Error  22:16:04 msg_show.emsg nvim-treesitter[ocaml_mlx]: Error during download, please verify your internet connection
22:16:04 msg_show fatal: repository '~/Workspace/tree-sitter-mlx' does not exist

How this supposed to work at all if the path is hardcoded? 
https://github.com/ocaml-mlx/ocaml_mlx.nvim/blob/main/lua/ocaml_mlx.lua#L13

**Comment by dmtrKovalenko** [comment]
It started working when I manually cloned treesitter into the hardcoded path

**Comment by andreypopp** [comment]
Sorry for that, pushed a fix https://github.com/ocaml-mlx/ocaml_mlx.nvim/commit/7edfefcc8254ddc32a6ee243b5205b8bf3b76f40
